version: "3.4"
name: nexus-app

services:
  web:
    build: .
    container_name: nexus-app
    restart: unless-stopped
    ports:
      # http://localhost:8081
      - "8081:80"
#  web:
#    image: ghcr.io/digital-blueprint/nexus-app:latest
#    container_name: nexus-app
#    restart: always
#    ports:
#      - "8081:80"
